---
extends:
  - plugin:@typescript-eslint/recommended

rules:
  '@typescript-eslint/no-empty-interface': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-member-accessibility': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-unused-vars': 'off'
  '@typescript-eslint/no-use-before-define': 'off'
  '@typescript-eslint/array-type': ['error', { default: 'generic' }]
